[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = true

[programs.devnet]
takesfun = "4D1RaYpBgEAj437RBaCkbKkpN2S2BA4CcmkE35MR1CZv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=d4602612-225a-400a-a286-1dd8fc2b378b"
wallet = "./keys/admin.json"

[scripts]
build = "rm -rf target && anchor build && mkdir -p target/deploy && cp ./keys/program/3uHJMHzeiqdqQ3LNc5bNVxuCp224HGtStPkv1JUEcabr.json ./target/deploy/takesfun-keypair.json"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
